[package]
name = "minigrep-new"
version = "0.1.0"
edition = "2021"
authors = ["Murtaza Nazar <mkm9284@gmail.con>"]
description = "A simple command-line tool for searching text in files"
license = "MIT"
repository = "https://github.com/MurtadaNazar/minigrep"
documentation = "https://docs.rs/minigrep"
readme = "README.md"
keywords = ["cli", "search", "grep", "text"]
categories = ["command-line-utilities", "text-processing"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
regex = "1.9.5"

[dev-dependencies]
tempfile = "3.8.0"
serial_test = "2.0.0"
